# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title-bold: "#UCDPSS23"
title-normal: 2023 UC Davis Plant Sciences Symposium
email: 
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "pbgso.github.io" # the base hostname & protocol for your site
author: Kyle Rizzo
street_address: UC Davis Alumni Center
city: Davis
state: CA
zip_code: 95616
country: United States of America
phone: 

force-https: True

# Plugins
gems:
  - jekyll-sitemap
  - jemoji

# Homepage tiles
tiles-source: pages # accepts "posts" or "pages" 
tiles-count: 7

# Social settings
500px_url: 
facebook_url: 

# Build settings
markdown: kramdown

